services:
  caddy:
    container_name: caddy
    image: caddy:2
    ports:
      - 8080:8080
    links:
      - typonamer
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/typonamer
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - typonamer
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  typonamer:
    container_name: typonamer
    image: golang:1
    command: /typonamer/typonamer
    volumes:
      - ./backend:/typonamer
    links:
      - redis
    environment:
      - TZ=Asia/Shanghai
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - APP_TUNING=true
    depends_on:
      - redis
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  redis:
    image: redis:7
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/redisdata:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
